### ISSUE TITLE
localhost not working anymore in Update SSM v1.0.27

### ISSUE THREAD

**Issue by Sarpendon** [mrhid6/SatisfactoryServerManager#115]
Updated via .\install.ps1 -update $true since then "This site can’t be reached localhost refused to connect."

**Comment by mrhid6** [comment]
Does it say which site its trying to connect to?

**Comment by Sarpendon** [comment]
http://localhost:3000/
This site can’t be reached
localhost refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by Sarpendon** [comment]
rollback to 1.0.24 works again perfect. Thank you
