### ISSUE TITLE
Error: This version of Linux is not supported for SSM on Debian 10.11

### ISSUE THREAD

**Issue by Allread** [mrhid6/SatisfactoryServerManager#118]
Hello :) 
I've this error message : 

![image](https://user-images.githubusercontent.com/16807391/141152318-6ec61fbc-d0c2-45d2-8a49-593faf893c4c.png)

on Debian 10.11

_root@SERVEUR:/home# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"_

**Comment by mrhid6** [comment]
Hi @Allread i will have a look in a bit :)
