### ISSUE TITLE
No SSM.json file

### ISSUE THREAD

**Issue by yao89** [mrhid6/SatisfactoryServerManager#126]
Hi,
After installation, I don't got this file, so I can't configure :
/home/ssm/.SatisfactoryServerManager/SSM.json

Do you know why, and maybe how can I add it manually ?

Thanks

**Comment by mrhid6** [comment]
If SSM has started correctly you can go to the settings page and edit any setting and save it should create the file.

**Comment by yao89** [comment]
Not at all, I can't access SSM, try lots of things from 2 days....

**Comment by yao89** [comment]
![image](https://user-images.githubusercontent.com/4552011/142770842-8646078d-74b4-4c8a-8de9-b1a2faca428d.png)

**Comment by mrhid6** [comment]
You can run it manually by running /opt/SSM/SatisfactoryServerManager and see what errors show up

**Comment by yao89** [comment]
Looks like a got an other missing with GLIBC...
![image](https://user-images.githubusercontent.com/4552011/142771013-8eab434f-5210-43ec-91fb-dce627bd03e4.png)

**Comment by mrhid6** [comment]
Hmm I’m just out of the house right now so will take a look when I’m home

**Comment by yao89** [comment]
Thanks 🙂 
Here the versions I got, i'll continue to search
![image](https://user-images.githubusercontent.com/4552011/142771187-49c0e659-a6aa-4c49-bcf9-070a6ca6f2c6.png)

**Comment by mrhid6** [comment]
@yao89 what version of Ubuntu are you running

**Comment by yao89** [comment]
That's the point I think. The server run 18.04 LTS.
There was lots of problem for upgrade....

I'm now upgrading to 20.04, i'll see if it's ok after.

**Comment by yao89** [comment]
It's ok !

So, maybe you need to make Ubuntu 20.04 a prereq ;)

An other question : Does SSM install itself an dedicated server when you "Create server", or do I need to install it manually, then tell SSM where it is ?
I've started with doing one manually, then now i think to understand that was not useful..

**Comment by mrhid6** [comment]
@yao89 is this issue fixed now? 
Go to servers page and click Create Server, once it’s running and active click the cog button to the right and go to the bottom there is a Install/reinstall button. Go to the Logs page and select the new server and monitor SSM Logs section for install completed log message

**Comment by mrhid6** [comment]
The logs page will auto refresh every 20 seconds or so

**Comment by yao89** [comment]
I have make a new fresh install of Ubuntu, because nothing was working here.
So, new server, but got an error line 114, tried to do the command manually :
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC

Command 'strings' not found, but can be installed with:

sudo apt install binutils
```

Maybe add this to the bash file

**Comment by yao89** [comment]
ALL GOOD ! Finally 🙂

Thanks for your super job here with SSM, and for your help ;)

Maybe I will make an little tutorial video to make a new server working.

**Comment by mrhid6** [comment]
Should already be there https://github.com/mrhid6/SatisfactoryServerManager/blob/6343c3ffcbff590d2f85444dc7bb1613304660ae/install.sh#L97

**Comment by yao89** [comment]
Ahem... really weird.
Maybe because I run the script as admin(sudo), not as root the first time.
