### ISSUE TITLE
Where are logs for SSM Agent ?

### ISSUE THREAD

**Issue by yao89** [mrhid6/SatisfactoryServerManager#128]
I got problem to activate server, but can't understand what's happening.
I select the green arrow in Servers tab, it start Running, then seems to crash.
I can't find useful logs. Only /home/ssm/.SatisfactoryServerManager/logs but there is nothing else than 
`2021-11-22 19:59:02.478 INFO  [AGENT_HANDLER] - Starting Agent... 
2021-11-22 19:59:02.297 INFO  [AGENT_HANDLER] - Agent Started! 
2021-11-22 20:00:14.259 INFO  [AGENT_HANDLER] - Starting Agent... 
2021-11-22 20:00:14.615 INFO  [AGENT_HANDLER] - Agent Started! `

I tried to create a new server, same.

**Comment by mrhid6** [comment]
You can start the SSMAgent manually to see what errors are being thrown by running `docker run -it SSMAgent1`

**Comment by mrhid6** [comment]
Updated command ^

**Comment by mrhid6** [comment]
@yao89 is this still an issue?

**Comment by yao89** [comment]
Hi, no more issue, but no more use of server until they support mods... Play without mode is... ahem... not as good ;)
