### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by GitWolf0** [mrhid6/SatisfactoryServerManager#135]
The Windows binaries immediately closes off with the following error: `connect ECONNREFUSED 127.0.0.1:2375`
All ports are forwarded, even tried disabling the firewall and testing on 3 machines; Windows Server 2022, W10 and W11.

**Comment by mrhid6** [comment]
You need to open docker desktop and enable expose docker Deamon in the settings page

**Comment by GitWolf0** [comment]
Thank you, worked perfectly!
