### ISSUE TITLE
Invalid Login Credentials!

### ISSUE THREAD

**Issue by GeorgePratt** [mrhid6/SatisfactoryServerManager#149]
Changed the ssm.json before first time logging in and when I put in the password that I changed it to in the json it keeps telling me the login credentials are invalid. Is this an issue with changing the  json before logging in the first time? I've changed it to alpha-numeric with a symbol, alpha-numeric only, and even a blank password but all I get is "Invalid Login Credentials!"

**Comment by mrhid6** [comment]
Stop SSM server then change the SSM.json password back to the default (ssm), the password in the config file is encrypted so it needs to be `209a221fa0090f144de33f88ab3fd88d`

Once thats set start the service again and enter the default password it will ask you to reset it through the web page.

**Comment by mrhid6** [comment]
If you are trying to add a new user please wait as we are currently working on a new user management system and will be available soon :)

**Comment by GeorgePratt** [comment]
Not trying to add users, just was wondering why you gave me the ability to change the json directly and by doing so I broke it utterly. You should probably not tell people to change the json directly unless it's to change the localhost port. That's the only safe thing to change it looks like. XD

**Comment by mrhid6** [comment]
I will add it to the github readme :) let me know if that worked

**Comment by GeorgePratt** [comment]
Still can't login. Giving me "Invalid Login Credentials!" using the default key and by not inputting any password in the password field in my browser.

**Comment by mrhid6** [comment]
default credentials should be (case matters):
Username: admin
Password: ssm

**Comment by GeorgePratt** [comment]
ok, that worked
