### ISSUE TITLE
Prerequisite missing : package "jq"

### ISSUE THREAD

**Issue by MasterDiverM** [mrhid6/SatisfactoryServerManager#196]

**Comment by mrhid6** [comment]
@MasterDiverM would be able to provide more information about the error you are getting?

**Comment by MasterDiverM** [comment]
When I make a new VM and install SMM, the package "jq" also needs to be installed, the SMM installer script gives an error that it cannot execute "jq"

**Comment by mrhid6** [comment]
@MasterDiverM Thanks what operating system and version are you running?

**Comment by MasterDiverM** [comment]
latest Ubuntu server 20.04 LTS

**Comment by mrhid6** [comment]
@MasterDiverM JQ should be installed as part of the [install script ](https://github.com/mrhid6/SatisfactoryServerManager/blob/9233bbd3be023911d4815c10c6b12e0d6ab30ee2/install.sh#L92)
