### ISSUE TITLE
SatisfactoryServerManager service constantly changing status from starting to running to starting ect.

### ISSUE THREAD

**Issue by MastarVS** [mrhid6/SatisfactoryServerManager#205]
I followed the guide to install but when installed the service is constantly changing.

Also experiencing the same error as earlier mentioned :install.ps1 error: "SSM: Unexpected status SERVICE_START_PENDING in response to START control.
When i use the solution of Mrhid6 nothing is working.

I also saw that Docker is not seeing any environment running.
Can someone help me?

**Comment by mrhid6** [comment]
Hi @MastarVS would you be able to attach what you are seeing on the install output? You can also run SSM without a service to debug what might be causing the service to stop working by navigating to `C:\Program Files\SSM` with a command prompt and doing `./SatisfactoryServerManager.exe`

**Comment by MastarVS** [comment]
![image](https://user-images.githubusercontent.com/106084894/169825576-99468e20-4d1a-4a1e-a558-7eda566a8f71.png)
You mean like this?

**Comment by MastarVS** [comment]
![image](https://user-images.githubusercontent.com/106084894/169825855-4155a527-2c69-432d-aac1-add109f2979b.png)

**Comment by mrhid6** [comment]
If you open Docker Desktop and verify this checkbox is selected 
![image](https://user-images.githubusercontent.com/666348/169826139-88e81bcd-2e0b-45d1-9ec3-f1ced385972b.png)

**Comment by mrhid6** [comment]
The install script should automatically set this but maybe it's not correctly set?

**Comment by MastarVS** [comment]
![image](https://user-images.githubusercontent.com/106084894/169826299-b23703ff-bad4-4b81-9a68-615edfea07f1.png)

**Comment by MastarVS** [comment]
It was already on.

**Comment by mrhid6** [comment]
Ah find the Docker service in windows services and restart it, make sure Docker desktop is fully closed before hand then give it a try.

**Comment by mrhid6** [comment]
> Done, still the same error.

When you run from the command prompt?

**Comment by MastarVS** [comment]
Yep!

**Comment by MastarVS** [comment]
![image](https://user-images.githubusercontent.com/106084894/169827190-f54729e1-007e-4fae-a8f3-5007241fae6b.png)

**Comment by mrhid6** [comment]
Hmm strange would you be able to restart your pc and see if that helps?

**Comment by MastarVS** [comment]
Already done it.
I can try it again later because there are players online right now.

**Comment by MastarVS** [comment]
I will try that! 
The strange thing is that i can't see if there is some server is installed in Docker.
Where can i check that?

**Comment by MastarVS** [comment]
> > Done, still the same error.
> 
> When you run from the command prompt?

Lol, didn't start up Docker Desktop after restart. 
It is starting now as it appears.

**Comment by mrhid6** [comment]
That's excellent news! SSM will install the Core on the server with each Server instance (SSMAgent) using docker containers. SSM Agents hold the SF dedicated server install and will run on the docker containers.

**Comment by MastarVS** [comment]
Thanks for that info! 
Where can i create my username?

**Comment by MastarVS** [comment]
Works! Thank you!
