### ISSUE TITLE
Server broken ...

### ISSUE THREAD

**Issue by yao89** [mrhid6/SatisfactoryServerManager#228]
Hi (again),

After long time, we want to try again SSM, but when I tried to update it, I think something broken all.
As you can see here, nothing well happend : http://193.190.64.69:3000/

If I try to update with wget -q https://git.io/Je7rx -O - | bash /dev/stdin "--update", it tell me that is it UTD, and just install, it's already installed.
I haven't found the way to reinstall or remove.

Can you help us ? 🙂

**Comment by yao89** [comment]
Hi, it seems to have reload it self during the night...
But now, I can't create a new server, but don't find logs.
Here you can see : https://streamable.com/yfpo3x

Thanks in advance

**Comment by mrhid6** [comment]
Hi @yao89 If you open the chrome dev tools it should give you a reason why it couldnt create the server. please could you send that to me?

**Comment by mrhid6** [comment]
You can also find the log files for SSM at `/home/ssm/logs/SSM` on linux or `C:\ProgramData\logs\SSM` on windows.

Or alternatively, you can go to the Admin page and Generate Debug Report

**Comment by yao89** [comment]
ERROREACCES: permission denied, mkdir '/SSMAgents/SSMAgent_Adri/SSM'

I search how, and to who give the permission to right, but can't figure out. To ssm user ? Should I create this /SSSAgents manually ?

**Comment by yao89** [comment]
Well, I give 777 permissions to this folder, to test. It's working, but if you can tell me who need what rights to this folder, it will be better.

Now I got a new problem, of course. Can't start the server. After some waiting, I got this error, without more info : ERRORDocker Failed To Start

Maybe the simplier is to reinstall completely SSM. Is there a way to do this ?

**Comment by mrhid6** [comment]
I can see the mistake in the install script [here](https://github.com/mrhid6/SatisfactoryServerManager/blob/58051834c4f37073be5aa55068de05ca5c4b59ed/install.sh#L169-L177)

Basically we changed the User id of ssm as it was conflicting I have fixed the script so give it 5 mins and try an upgrade

**Comment by mrhid6** [comment]
`ERROR Docker Failed To Start` Comes from the `WaitForContainerToStart` function and times out.

@yao89 I agree the best option would be to reinstall SSM
You can uninstall by doing the following:

```
SSM_SERVICENAME="SSM.service"
SSM_SERVICEFILE="/etc/systemd/system/SSM.service"
systemctl stop ${SSM_SERVICENAME}
systemctl disable ${SSM_SERVICENAME} 
rm -r "${SSM_SERVICEFILE}"
systemctl daemon-reload

rm -r /opt/SSM
deluser --remove-home ssm
rm -r /home/ssm
rm -r /SSMAgents
```

**Comment by mrhid6** [comment]
@yao89 Created an uninstall script [here](https://github.com/mrhid6/SatisfactoryServerManager#how-to-uninstall)

**Comment by yao89** [comment]
You're awesome !

Manual uninstall and reinstall work perfectly 👌🏻

Thanks, as usual, for your help ;)

**Comment by mrhid6** [comment]
That's great news thanks for letting me know. As you know SSM changes quite a bit with each version we release, so bugs are bound to show up.
